name: LaTeX Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-english

      - name: Compile LaTeX Document
        run: |
          pdflatex -interaction=nonstopmode -synctex=1 cv.tex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv-pdf
          path: cv.pdf
